server:
  port: 8080
  shutdown: graceful

spring:
  profiles:
    active: dev
  application:
    name: "toolkits-web"
  lifecycle:
    timeout-per-shutdown-phase: 15s
  web:
    resources:
      add-mappings: false
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.56:3308/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  data:
    redis:
      # 地址
      host: 192.168.1.56
      # 端口，默认为6379
      port: 30379
      # 密码
      password: 123456
      database: 0
      # 连接超时时间
      timeout: 500
      connect-timeout: 100
  async:
    enabled: true
    pool:
      core: 2
      max: 4
      queue: 100
      thread-name-prefix: "async-task-"
      await-termination-millis: 5000
      wait-for-tasks-to-complete-on-shutdown: true
  scheduling:
    enabled: true
    pool:
      size: 2
      thread-name-prefix: "scheduled-task-"
      await-termination-millis: 5000
      wait-for-tasks-to-complete-on-shutdown: true

management:
  server:
    # 指定监端点暴露监听端口
    port: 9001
  endpoints:
    web:
      exposure:
        include: "health, info, shutdown, mappings, metrics, loggers"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
